---
- name: stop when system is already on newest version
  ansible.builtin.fail:
    msg: "Server is already on newest version, stopping here!"
  when: ansible_distribution_release == proxmox_newest_deb_relase

- name: include OS specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
      paths:
        - "vars"

- name: gather facts and check prerequisites
  ansible.builtin.include_tasks:
    file: prepare.yml

- name: perform tasks for Proxmox Backup Server
  ansible.builtin.include_tasks:
    file: upgrade-pbs.yml
  when: is_pbs_role

- name: perform tasks for Proxmox Virtual Environment Server
  ansible.builtin.include_tasks:
    file: upgrade-pve.yml
  when: is_pve_role